// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_lite_support/cc/task/vision/proto/image_embedder_options.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "tensorflow/lite/experimental/acceleration/configuration/configuration.pb.h"
#include "tensorflow_lite_support/cc/task/core/proto/external_file.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto;
namespace tflite {
namespace task {
namespace vision {
class ImageEmbedderOptions;
struct ImageEmbedderOptionsDefaultTypeInternal;
extern ImageEmbedderOptionsDefaultTypeInternal _ImageEmbedderOptions_default_instance_;
}  // namespace vision
}  // namespace task
}  // namespace tflite
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace tflite {
namespace task {
namespace vision {

// ===================================================================


// -------------------------------------------------------------------

class ImageEmbedderOptions final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tflite.task.vision.ImageEmbedderOptions) */ {
 public:
  inline ImageEmbedderOptions() : ImageEmbedderOptions(nullptr) {}
  ~ImageEmbedderOptions() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ImageEmbedderOptions(::google::protobuf::internal::ConstantInitialized);

  ImageEmbedderOptions(const ImageEmbedderOptions& from);
  ImageEmbedderOptions(ImageEmbedderOptions&& from) noexcept
    : ImageEmbedderOptions() {
    *this = ::std::move(from);
  }

  inline ImageEmbedderOptions& operator=(const ImageEmbedderOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageEmbedderOptions& operator=(ImageEmbedderOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageEmbedderOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageEmbedderOptions* internal_default_instance() {
    return reinterpret_cast<const ImageEmbedderOptions*>(
               &_ImageEmbedderOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImageEmbedderOptions& a, ImageEmbedderOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageEmbedderOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageEmbedderOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageEmbedderOptions* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImageEmbedderOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImageEmbedderOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ImageEmbedderOptions& from) {
    ImageEmbedderOptions::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageEmbedderOptions* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "tflite.task.vision.ImageEmbedderOptions";
  }
  protected:
  explicit ImageEmbedderOptions(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kComputeSettingsFieldNumber = 8,
    kModelFileWithMetadataFieldNumber = 9,
    kL2NormalizeFieldNumber = 6,
    kQuantizeFieldNumber = 2,
    kNumThreadsFieldNumber = 7,
  };
  // optional .tflite.proto.ComputeSettings compute_settings = 8;
  bool has_compute_settings() const;
  void clear_compute_settings() ;
  const ::tflite::proto::ComputeSettings& compute_settings() const;
  PROTOBUF_NODISCARD ::tflite::proto::ComputeSettings* release_compute_settings();
  ::tflite::proto::ComputeSettings* mutable_compute_settings();
  void set_allocated_compute_settings(::tflite::proto::ComputeSettings* value);
  void unsafe_arena_set_allocated_compute_settings(::tflite::proto::ComputeSettings* value);
  ::tflite::proto::ComputeSettings* unsafe_arena_release_compute_settings();

  private:
  const ::tflite::proto::ComputeSettings& _internal_compute_settings() const;
  ::tflite::proto::ComputeSettings* _internal_mutable_compute_settings();

  public:
  // optional .tflite.task.core.ExternalFile model_file_with_metadata = 9;
  bool has_model_file_with_metadata() const;
  void clear_model_file_with_metadata() ;
  const ::tflite::task::core::ExternalFile& model_file_with_metadata() const;
  PROTOBUF_NODISCARD ::tflite::task::core::ExternalFile* release_model_file_with_metadata();
  ::tflite::task::core::ExternalFile* mutable_model_file_with_metadata();
  void set_allocated_model_file_with_metadata(::tflite::task::core::ExternalFile* value);
  void unsafe_arena_set_allocated_model_file_with_metadata(::tflite::task::core::ExternalFile* value);
  ::tflite::task::core::ExternalFile* unsafe_arena_release_model_file_with_metadata();

  private:
  const ::tflite::task::core::ExternalFile& _internal_model_file_with_metadata() const;
  ::tflite::task::core::ExternalFile* _internal_mutable_model_file_with_metadata();

  public:
  // optional bool l2_normalize = 6;
  bool has_l2_normalize() const;
  void clear_l2_normalize() ;
  bool l2_normalize() const;
  void set_l2_normalize(bool value);

  private:
  bool _internal_l2_normalize() const;
  void _internal_set_l2_normalize(bool value);

  public:
  // optional bool quantize = 2;
  bool has_quantize() const;
  void clear_quantize() ;
  bool quantize() const;
  void set_quantize(bool value);

  private:
  bool _internal_quantize() const;
  void _internal_set_quantize(bool value);

  public:
  // optional int32 num_threads = 7 [default = 1];
  bool has_num_threads() const;
  void clear_num_threads() ;
  ::int32_t num_threads() const;
  void set_num_threads(::int32_t value);

  private:
  ::int32_t _internal_num_threads() const;
  void _internal_set_num_threads(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:tflite.task.vision.ImageEmbedderOptions)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5, 2, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::tflite::proto::ComputeSettings* compute_settings_;
    ::tflite::task::core::ExternalFile* model_file_with_metadata_;
    bool l2_normalize_;
    bool quantize_;
    ::int32_t num_threads_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ImageEmbedderOptions

// optional .tflite.task.core.ExternalFile model_file_with_metadata = 9;
inline bool ImageEmbedderOptions::has_model_file_with_metadata() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.model_file_with_metadata_ != nullptr);
  return value;
}
inline const ::tflite::task::core::ExternalFile& ImageEmbedderOptions::_internal_model_file_with_metadata() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::tflite::task::core::ExternalFile* p = _impl_.model_file_with_metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::tflite::task::core::ExternalFile&>(::tflite::task::core::_ExternalFile_default_instance_);
}
inline const ::tflite::task::core::ExternalFile& ImageEmbedderOptions::model_file_with_metadata() const {
  // @@protoc_insertion_point(field_get:tflite.task.vision.ImageEmbedderOptions.model_file_with_metadata)
  return _internal_model_file_with_metadata();
}
inline void ImageEmbedderOptions::unsafe_arena_set_allocated_model_file_with_metadata(::tflite::task::core::ExternalFile* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.model_file_with_metadata_);
  }
  _impl_.model_file_with_metadata_ = reinterpret_cast<::tflite::task::core::ExternalFile*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tflite.task.vision.ImageEmbedderOptions.model_file_with_metadata)
}
inline ::tflite::task::core::ExternalFile* ImageEmbedderOptions::release_model_file_with_metadata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::tflite::task::core::ExternalFile* released = _impl_.model_file_with_metadata_;
  _impl_.model_file_with_metadata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::tflite::task::core::ExternalFile* ImageEmbedderOptions::unsafe_arena_release_model_file_with_metadata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:tflite.task.vision.ImageEmbedderOptions.model_file_with_metadata)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::tflite::task::core::ExternalFile* temp = _impl_.model_file_with_metadata_;
  _impl_.model_file_with_metadata_ = nullptr;
  return temp;
}
inline ::tflite::task::core::ExternalFile* ImageEmbedderOptions::_internal_mutable_model_file_with_metadata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.model_file_with_metadata_ == nullptr) {
    auto* p = CreateMaybeMessage<::tflite::task::core::ExternalFile>(GetArenaForAllocation());
    _impl_.model_file_with_metadata_ = reinterpret_cast<::tflite::task::core::ExternalFile*>(p);
  }
  return _impl_.model_file_with_metadata_;
}
inline ::tflite::task::core::ExternalFile* ImageEmbedderOptions::mutable_model_file_with_metadata() {
  ::tflite::task::core::ExternalFile* _msg = _internal_mutable_model_file_with_metadata();
  // @@protoc_insertion_point(field_mutable:tflite.task.vision.ImageEmbedderOptions.model_file_with_metadata)
  return _msg;
}
inline void ImageEmbedderOptions::set_allocated_model_file_with_metadata(::tflite::task::core::ExternalFile* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.model_file_with_metadata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.model_file_with_metadata_ = reinterpret_cast<::tflite::task::core::ExternalFile*>(value);
  // @@protoc_insertion_point(field_set_allocated:tflite.task.vision.ImageEmbedderOptions.model_file_with_metadata)
}

// optional bool l2_normalize = 6;
inline bool ImageEmbedderOptions::has_l2_normalize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ImageEmbedderOptions::clear_l2_normalize() {
  _impl_.l2_normalize_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool ImageEmbedderOptions::l2_normalize() const {
  // @@protoc_insertion_point(field_get:tflite.task.vision.ImageEmbedderOptions.l2_normalize)
  return _internal_l2_normalize();
}
inline void ImageEmbedderOptions::set_l2_normalize(bool value) {
  _internal_set_l2_normalize(value);
  // @@protoc_insertion_point(field_set:tflite.task.vision.ImageEmbedderOptions.l2_normalize)
}
inline bool ImageEmbedderOptions::_internal_l2_normalize() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.l2_normalize_;
}
inline void ImageEmbedderOptions::_internal_set_l2_normalize(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.l2_normalize_ = value;
}

// optional bool quantize = 2;
inline bool ImageEmbedderOptions::has_quantize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ImageEmbedderOptions::clear_quantize() {
  _impl_.quantize_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool ImageEmbedderOptions::quantize() const {
  // @@protoc_insertion_point(field_get:tflite.task.vision.ImageEmbedderOptions.quantize)
  return _internal_quantize();
}
inline void ImageEmbedderOptions::set_quantize(bool value) {
  _internal_set_quantize(value);
  // @@protoc_insertion_point(field_set:tflite.task.vision.ImageEmbedderOptions.quantize)
}
inline bool ImageEmbedderOptions::_internal_quantize() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.quantize_;
}
inline void ImageEmbedderOptions::_internal_set_quantize(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.quantize_ = value;
}

// optional int32 num_threads = 7 [default = 1];
inline bool ImageEmbedderOptions::has_num_threads() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ImageEmbedderOptions::clear_num_threads() {
  _impl_.num_threads_ = 1;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ImageEmbedderOptions::num_threads() const {
  // @@protoc_insertion_point(field_get:tflite.task.vision.ImageEmbedderOptions.num_threads)
  return _internal_num_threads();
}
inline void ImageEmbedderOptions::set_num_threads(::int32_t value) {
  _internal_set_num_threads(value);
  // @@protoc_insertion_point(field_set:tflite.task.vision.ImageEmbedderOptions.num_threads)
}
inline ::int32_t ImageEmbedderOptions::_internal_num_threads() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.num_threads_;
}
inline void ImageEmbedderOptions::_internal_set_num_threads(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.num_threads_ = value;
}

// optional .tflite.proto.ComputeSettings compute_settings = 8;
inline bool ImageEmbedderOptions::has_compute_settings() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.compute_settings_ != nullptr);
  return value;
}
inline const ::tflite::proto::ComputeSettings& ImageEmbedderOptions::_internal_compute_settings() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::tflite::proto::ComputeSettings* p = _impl_.compute_settings_;
  return p != nullptr ? *p : reinterpret_cast<const ::tflite::proto::ComputeSettings&>(::tflite::proto::_ComputeSettings_default_instance_);
}
inline const ::tflite::proto::ComputeSettings& ImageEmbedderOptions::compute_settings() const {
  // @@protoc_insertion_point(field_get:tflite.task.vision.ImageEmbedderOptions.compute_settings)
  return _internal_compute_settings();
}
inline void ImageEmbedderOptions::unsafe_arena_set_allocated_compute_settings(::tflite::proto::ComputeSettings* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.compute_settings_);
  }
  _impl_.compute_settings_ = reinterpret_cast<::tflite::proto::ComputeSettings*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tflite.task.vision.ImageEmbedderOptions.compute_settings)
}
inline ::tflite::proto::ComputeSettings* ImageEmbedderOptions::release_compute_settings() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::tflite::proto::ComputeSettings* released = _impl_.compute_settings_;
  _impl_.compute_settings_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::tflite::proto::ComputeSettings* ImageEmbedderOptions::unsafe_arena_release_compute_settings() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:tflite.task.vision.ImageEmbedderOptions.compute_settings)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::tflite::proto::ComputeSettings* temp = _impl_.compute_settings_;
  _impl_.compute_settings_ = nullptr;
  return temp;
}
inline ::tflite::proto::ComputeSettings* ImageEmbedderOptions::_internal_mutable_compute_settings() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.compute_settings_ == nullptr) {
    auto* p = CreateMaybeMessage<::tflite::proto::ComputeSettings>(GetArenaForAllocation());
    _impl_.compute_settings_ = reinterpret_cast<::tflite::proto::ComputeSettings*>(p);
  }
  return _impl_.compute_settings_;
}
inline ::tflite::proto::ComputeSettings* ImageEmbedderOptions::mutable_compute_settings() {
  ::tflite::proto::ComputeSettings* _msg = _internal_mutable_compute_settings();
  // @@protoc_insertion_point(field_mutable:tflite.task.vision.ImageEmbedderOptions.compute_settings)
  return _msg;
}
inline void ImageEmbedderOptions::set_allocated_compute_settings(::tflite::proto::ComputeSettings* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.compute_settings_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.compute_settings_ = reinterpret_cast<::tflite::proto::ComputeSettings*>(value);
  // @@protoc_insertion_point(field_set_allocated:tflite.task.vision.ImageEmbedderOptions.compute_settings)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace vision
}  // namespace task
}  // namespace tflite


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_tensorflow_5flite_5fsupport_2fcc_2ftask_2fvision_2fproto_2fimage_5fembedder_5foptions_2eproto_2epb_2eh
